name: Boostit
favicon: null
layout_spectrum: 0.849575084168464
typography_spectrum: 0.7700697269756347
title: 'Your Digital Partner - DIGITAL ADVISING & TRAINING'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-67831803-2
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.5112250968813896
  lightness: 0.422091644955799
  saturation: 0.39852672745473683
  rhythmicContrast: 0.31983067793771625
purpose: []
