name: Boostit
favicon: null
layout_spectrum: 0.849575084168464
typography_spectrum: 0.7700697269756347
title: Your Digital Partner
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-67831803-2
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#2a69ab'
    - '#87aacf'
  brandStrength: 0
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
purpose: []
